--- 
author: 
  name: "Omer Javed"
avatar: /img/oj.jpg
baseurl: ""
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      comments: true
      layout: post
      social-share: true
  - 
    scope: 
      path: ""
    values: 
      layout: page
      show-avatar: true
description: "Python Developer | Aspiring Data Scientist | ML Engineer"
excerpt_length: 50
exclude: 
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
footer-col: "#F5F5F5"
footer-link-col: "#404040"
footer-text-col: "#777777"
highlighter: rouge
hover-col: "#0085A1"
kramdown: 
  input: GFM
link-col: "#008AFF"
link-tags: true
markdown: kramdown
navbar-children-col: "#F5F5F5"
navbar-col: "#F5F5F5"
navbar-links: 
  - title: Group 1
    subfolderitems:
      - page: Thing 1
        url: /thing1.html
      - page: Thing 2
        url: /thing2.html
      - page: Thing 3
        url: /thing3.html
  - title: Group 2
    subfolderitems:
      - page: Piece 1
        url: /piece1.html
      - page: Piece 2
        url: /piece2.html
      - page: Piece 3
        url: /piece3.html
  - title: Group 3
    subfolderitems:
      - page: Widget 1
        url: /widget1.html
      - page: Widget 2
        url: /widget2.html
      - page: Widget 3
        url: /widget3.html

      
navbar-text-col: "#404040"
page-col: "#FFFFFF"
paginate: 5
permalink: "/:year-:month-:day-:title/"
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
prose: 
  ignore: 
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  media: img
  metadata: 
    _posts: 
      - 
        field: 
          element: hidden
          value: post
        name: layout
      - 
        field: 
          alterable: true
          element: text
          label: "Post title"
          placeholder: Title
        name: title
      - 
        field: 
          alterable: true
          element: textarea
          label: Subtitle
          placeholder: "A description of your post."
        name: subtitle
      - 
        field: 
          alterable: true
          element: text
          help: "Enter date of post."
          label: Date
          placeholder: yyyy-mm-dd
        name: date
      - 
        field: 
          alterable: true
          element: text
          help: "Add a thumbnail image to your post."
          label: Image
          placeholder: Thumbnail
        name: image
      - 
        field: 
          element: checkbox
          help: "Check to publish post, uncheck to hide."
          label: Publish
        name: published
  rooturl: _posts
share-links-active: 
  facebook: true
  google: false
  linkedin: true
  twitter: true
social-network-links: 
  email: omerjaved11@gmail.com
  facebook: omerjaved1337
  github: omerjaved11
  linkedin: omerjaved11
  stackoverflow: 11028742/omer-javed
  twitter: omerjaved111
staticman: 
  branch: ~
  endpoint: ~
  reCaptcha: 
    secret: ~
    siteKey: ~
  repository: ~
timezone: America/Vancouver
title: "Omer Javed"
title-separator: "-"
url: "https://omerjaved11.github.io"
url-pretty: omerjaved.me
